services:
  postgres:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-portfolio_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-portfolio_pass}
      POSTGRES_DB:       ${POSTGRES_DB:-portfolio_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-portfolio_user} -d ${POSTGRES_DB:-portfolio_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  backend:
    build:
      context: ./backend
    container_name: portfolio_backend
    restart: unless-stopped
    environment:
      NODE_ENV:       production
      PORT:           5000
      DATABASE_URL:   postgresql://${POSTGRES_USER:-portfolio_user}:${POSTGRES_PASSWORD:-portfolio_pass}@postgres:5432/${POSTGRES_DB:-portfolio_db}
      JWT_SECRET:     ${JWT_SECRET:-dev_secret_ganti_ini_di_production}
      JWT_EXPIRES_IN: 7d
      DOMAIN:         ${DOMAIN:-https://farisalfatih.my.id}
    expose:
      - "5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
    container_name: portfolio_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal
      - proxy_default  # ← gabung ke network NPM

networks:
  internal:
    driver: bridge
  proxy_default:
    external: true  # ← pakai network NPM yang sudah ada

volumes:
  postgres_data:
  uploads_data:
